app_name: watsonx-code-reviewer
log_level: INFO
port: 8080
github:
  app_id: "YOUR_GITHUB_APP_ID"
  installation_id: "YOUR_GITHUB_INSTALLATION_ID"
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    YOUR_PRIVATE_KEY_CONTENT
    -----END RSA PRIVATE KEY-----
