app_name: watsonx-code-reviewer
log_level: DEBUG
port: 8888
github:
  app_id: "YOUR_GITHUB_APP_ID"
  installation_id: "YOUR_GITHUB_INSTALLATION_ID"
  review_label: "ready-to-review"  # Label used to trigger reviews
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    YOUR_PRIVATE_KEY_CONTENT
    -----END RSA PRIVATE KEY-----
